apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: social-network-dev

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: social-network-laravel

configMapGenerator:
- name: social-network-config
  behavior: merge
  literals:
  - APP_ENV=development
  - APP_DEBUG=true
  - LOG_LEVEL=debug

images:
- name: ghcr.io/liberusoftware/social-network-laravel
  newTag: develop
