apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- hpa.yaml

namespace: social-network-laravel

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: social-network-laravel

configMapGenerator:
- name: social-network-config
  behavior: merge
  literals:
  - APP_ENV=production
  - APP_DEBUG=false
  - LOG_LEVEL=warning

images:
- name: ghcr.io/liberusoftware/social-network-laravel
  newTag: latest
