apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: social-network-storage
  namespace: social-network-laravel
  labels:
    app: social-network-laravel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
