apiVersion: v1
kind: Service
metadata:
  name: social-network-laravel
  namespace: social-network-laravel
  labels:
    app: social-network-laravel
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: social-network-laravel
    component: application
